# Generated by Django 4.1.5 on 2023-02-09 18:06

import cloudinary.models
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('short_description', models.TextField(max_length=500)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('E', 'environmental monitoring'), ('S', 'signal conversion'), ('N', 'network'), ('T', 'Temperature monitoring')], max_length=50)),
                ('tags', models.CharField(max_length=50)),
                ('product_img1', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('product_img2', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('product_img3', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('product_img4', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('moredetails', tinymce.models.HTMLField()),
            ],
        ),
        migrations.CreateModel(
            name='Usecase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('EL', 'Electronics industry'), ('F', 'Food'), ('WT', 'Water treatment'), ('FM', 'Facility management'), ('SF', 'Smart Farm'), ('O', 'Oem'), ('PB', 'Pharmaceutical Bio'), ('PM', 'Precision machine')], max_length=50)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='electronics')),
            ],
        ),
    ]
