# Generated by Django 4.1.5 on 2023-02-09 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_product_category_alter_usecase_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('N', 'network'), ('T', 'Temperature monitoring'), ('S', 'signal conversion'), ('E', 'environmental monitoring')], max_length=50),
        ),
        migrations.AlterField(
            model_name='usecase',
            name='category',
            field=models.CharField(choices=[('PB', 'Pharmaceutical Bio'), ('PM', 'Precision machine'), ('O', 'Oem'), ('F', 'Food'), ('EL', 'Electronics industry'), ('SF', 'Smart Farm'), ('WT', 'Water treatment'), ('FM', 'Facility management')], max_length=50),
        ),
    ]
