# Generated by Django 4.1.5 on 2023-02-10 19:43

from django.db import migrations, models
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_product_category_alter_usecase_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usecase',
            name='description',
        ),
        migrations.RemoveField(
            model_name='usecase',
            name='image',
        ),
        migrations.AddField(
            model_name='usecase',
            name='moredetails',
            field=tinymce.models.HTMLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('N', 'network'), ('E', 'environmental monitoring'), ('T', 'Temperature monitoring'), ('S', 'signal conversion')], max_length=50),
        ),
        migrations.AlterField(
            model_name='usecase',
            name='category',
            field=models.CharField(choices=[('PM', 'Precision machine'), ('PB', 'Pharmaceutical Bio'), ('O', 'Oem'), ('F', 'Food'), ('FM', 'Facility management'), ('SF', 'Smart Farm'), ('WT', 'Water treatment'), ('EL', 'Electronics industry')], max_length=50),
        ),
    ]
