# Generated by Django 4.1.5 on 2023-02-10 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_usecase_description_remove_usecase_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usecase',
            name='title',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('E', 'environmental monitoring'), ('T', 'Temperature monitoring'), ('S', 'signal conversion'), ('N', 'network')], max_length=50),
        ),
        migrations.AlterField(
            model_name='usecase',
            name='category',
            field=models.CharField(choices=[('EL', 'Electronics industry'), ('F', 'Food'), ('FM', 'Facility management'), ('O', 'Oem'), ('SF', 'Smart Farm'), ('PB', 'Pharmaceutical Bio'), ('WT', 'Water treatment'), ('PM', 'Precision machine')], max_length=50),
        ),
    ]
