# Generated by Django 4.1.5 on 2023-02-10 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_usecase_title_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('N', 'network'), ('T', 'Temperature monitoring'), ('S', 'signal conversion'), ('E', 'environmental monitoring')], max_length=50),
        ),
        migrations.AlterField(
            model_name='usecase',
            name='category',
            field=models.CharField(choices=[('SF', 'Smart Farm'), ('O', 'Oem'), ('PM', 'Precision machine'), ('EL', 'Electronics industry'), ('FM', 'Facility management'), ('PB', 'Pharmaceutical Bio'), ('WT', 'Water treatment'), ('F', 'Food')], max_length=50),
        ),
    ]
