# Generated by Django 4.1.5 on 2023-02-11 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_product_category_alter_usecase_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('environmental_monitoring', 'environmental_monitoring'), ('signal_conversion', 'signal_conversion'), ('Temperature_monitoring', 'Temperature_monitoring'), ('network', 'network')], max_length=50),
        ),
        migrations.AlterField(
            model_name='usecase',
            name='category',
            field=models.CharField(choices=[('PB', 'Pharmaceutical Bio'), ('SF', 'Smart Farm'), ('FM', 'Facility management'), ('O', 'Oem'), ('WT', 'Water treatment'), ('EL', 'Electronics industry'), ('PM', 'Precision machine'), ('F', 'Food')], max_length=50),
        ),
    ]
