# Generated by Django 4.1.5 on 2023-02-12 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_product_category_alter_usecase_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('environmental_monitoring', 'environmental_monitoring'), ('signal_conversion', 'signal_conversion'), ('network', 'network'), ('Temperature_monitoring', 'Temperature_monitoring')], max_length=50),
        ),
        migrations.AlterField(
            model_name='usecase',
            name='category',
            field=models.CharField(choices=[('oem', 'Oem'), ('electronics_industry', 'Electronics_industry'), ('food', 'Food'), ('water_treatment', 'Water_treatment'), ('smart_Farm', 'Smart_Farm'), ('precision_machine', 'Precision_machine'), ('pharmaceutical_Bio', 'Pharmaceutical_Bio'), ('facility_management', 'Facility_management')], max_length=50),
        ),
    ]
