# Generated by Django 4.1.7 on 2023-02-25 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_product_category_alter_usecase_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('message', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Temperature_monitoring', 'Temperature_monitoring'), ('signal_conversion', 'signal_conversion'), ('environmental_monitoring', 'environmental_monitoring'), ('network', 'network')], max_length=50),
        ),
        migrations.AlterField(
            model_name='usecase',
            name='category',
            field=models.CharField(choices=[('pharmaceutical_Bio', 'Pharmaceutical_Bio'), ('precision_machine', 'Precision_machine'), ('electronics_industry', 'Electronics_industry'), ('water_treatment', 'Water_treatment'), ('food', 'Food'), ('smart_Farm', 'Smart_Farm'), ('oem', 'Oem'), ('facility_management', 'Facility_management')], max_length=50),
        ),
    ]
