# Generated by Django 4.1.7 on 2023-02-25 11:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_contact_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('network', 'network'), ('Temperature_monitoring', 'Temperature_monitoring'), ('environmental_monitoring', 'environmental_monitoring'), ('signal_conversion', 'signal_conversion')], max_length=50),
        ),
        migrations.AlterField(
            model_name='usecase',
            name='category',
            field=models.CharField(choices=[('water_treatment', 'Water_treatment'), ('precision_machine', 'Precision_machine'), ('oem', 'Oem'), ('facility_management', 'Facility_management'), ('pharmaceutical_Bio', 'Pharmaceutical_Bio'), ('smart_Farm', 'Smart_Farm'), ('electronics_industry', 'Electronics_industry'), ('food', 'Food')], max_length=50),
        ),
    ]
