# Generated by Django 4.1.7 on 2023-02-25 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_contact_created_at_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Temperature_monitoring', 'Temperature_monitoring'), ('environmental_monitoring', 'environmental_monitoring'), ('network', 'network'), ('signal_conversion', 'signal_conversion')], max_length=50),
        ),
        migrations.AlterField(
            model_name='usecase',
            name='category',
            field=models.CharField(choices=[('food', 'Food'), ('smart_Farm', 'Smart_Farm'), ('water_treatment', 'Water_treatment'), ('electronics_industry', 'Electronics_industry'), ('pharmaceutical_Bio', 'Pharmaceutical_Bio'), ('facility_management', 'Facility_management'), ('precision_machine', 'Precision_machine'), ('oem', 'Oem')], max_length=50),
        ),
    ]
